### ISSUE TITLE
Exporter plugin not working?

### ISSUE THREAD

**Issue by DebugBSD** [gameprogcpp/code#26]
I'm trying to install the plugin on my Blender (Version 2.79b) running on Windows 10 Pro and when I'm done installing the plugin (through File -> User Preferences -> Add-ons -> Install Add-on from File...) everything seems to be correct but, when I try to look for it on the add-ons Tab I don't see the plugin on the list. And there is no option in the File -> Export menu list. Maybe I'm doing something wrong? or the plugin has to be updated?

BTW: Nice book. I'm learning a lot with it.

**Comment by charmanderstrom** [comment]
I was having the same problem, looks like its a script and not an addon.  Next to the Help button there is a button with 3 rectangles,  Press it and select scripting.  Open the python script or paste it in and press run script.  Now i'm just having this issue that line 34 and 100 are giving me errors from the other Issue thread here it looks like I have to select them mesh but i can't get it working.

**Comment by chalonverse** [comment]
I made a short video showing how to use the plugin: https://www.youtube.com/watch?v=ukLQH_-IsLs

The main thing is if you're getting the line 34/100 error, it means you have the it selected in "edit" mode instead of "object" mode. If you make sure you're in object mode and have the object selected, it should work.

**Comment by charmanderstrom** [comment]
Wow thank you so much I wasn't expecting such help.  After tinkering with
it for a while it turns out I also forgot to give my objects in blender a
texture as well, *face palm*  Anyways you're book is great I'm having so
much fun working through it and learning lots too I really like the way it
is designed.

Thanks
